import { expect, test, type Page } from '@playwright/test';

/**
 * The money path, in a browser: bills → the slip → payouts → a run → savings.
 *
 * The unit tests prove the arithmetic and the refusals against the mock API. What only
 * a browser can confirm is that the screens built on them **render** — that the lazy
 * chunks resolve, the month picker validates a key against the API's own list rather
 * than trusting the URL, and the deep links between the three modules land somewhere.
 *
 * Signed in as the accountant, because §12.1 gives them `billing: W` and `payouts: W`
 * — the role the whole path was designed around. A clerk would see the same screens
 * with every control withheld, which is a different test.
 */

const ACCOUNTANT = 'accountant@galabodatea.lk';
const PASSWORD = 'demo1234';

async function signIn(page: Page) {
  await page.goto('/sign-in');
  await page.getByLabel(/^email$/i).fill(ACCOUNTANT);
  await page.getByLabel(/^password$/i).fill(PASSWORD);
  await page.getByRole('button', { name: /^sign in$/i }).click();
  await expect(page.getByRole('heading', { name: /dashboard/i })).toBeVisible({ timeout: 15_000 });
}

test('reads a month’s bills and opens one supplier’s slip', async ({ page }) => {
  await signIn(page);

  await page.getByRole('link', { name: /^bills$/i }).click();
  await expect(page.getByRole('heading', { name: /^bills$/i })).toBeVisible({ timeout: 15_000 });

  // The open month is the default, and it has no rate in the fixture — so the run
  // card must say what a run needs rather than offering a button that would fail.
  await expect(page.getByText(/no bills generated for/i)).toBeVisible({ timeout: 15_000 });

  // Switch to a published month, which the fixture generated bills for.
  const monthSelect = page.getByLabel(/^month$/i);
  const published = (await monthSelect.locator('option').last().getAttribute('value'))!;
  await monthSelect.selectOption(published);

  // A run summary, and a grid of bills ordered by supplier code.
  await expect(page.getByText(/generated by/i)).toBeVisible({ timeout: 15_000 });
  const grid = page.getByRole('table', { name: /^bills$/i });
  await expect(grid.locator('tbody tr').first()).toBeVisible({ timeout: 15_000 });

  // Open the slip.
  await grid.locator('tbody tr').first().click();
  await expect(page.getByRole('heading', { name: /green leaf account/i })).toBeVisible({
    timeout: 15_000,
  });

  // The nine deduction lines are all present, zeros included — the slip's shape.
  for (const label of [/transport charges/i, /^stamps$/i, /previous debts/i, /^savings$/i]) {
    await expect(page.getByText(label).first()).toBeVisible();
  }
  // And §21.8 is stated rather than left as a missing edit button.
  await expect(page.getByText(/open question with the factory/i).first()).toBeVisible();
});

test('reads a payout run and its lines', async ({ page }) => {
  await signIn(page);

  await page.getByRole('link', { name: /^payouts$/i }).click();
  await expect(page.getByRole('heading', { name: /^payouts$/i })).toBeVisible({ timeout: 15_000 });

  // The default is the latest **published** month — the opposite of the bills screen,
  // because a run against an open month is refused.
  const runs = page.getByRole('table', { name: /^payouts$/i });
  await expect(runs.locator('tbody tr').first()).toBeVisible({ timeout: 15_000 });

  // §21.17 as it now stands: the file exists, and what it is *not* is stated where
  // somebody would otherwise assume it was a SLIPS file.
  await expect(page.getByText(/download it as a file/i)).toBeVisible();
  await expect(page.getByText(/fixed-width bank format/i)).toBeVisible();

  await runs.locator('tbody tr').first().click();
  await expect(page.getByRole('heading', { name: /bank transfer|cheque|cash/i })).toBeVisible({
    timeout: 15_000,
  });

  // The line grid, and the account numbers on it are masked (§20.4).
  const lines = page.getByRole('table', { name: /^lines$/i });
  await expect(lines.locator('tbody tr').first()).toBeVisible({ timeout: 15_000 });
  await expect(lines.getByText(/^•+\d{4}$/).first()).toBeVisible();
});

test('reads the savings scheme and one supplier’s passbook', async ({ page }) => {
  await signIn(page);

  await page.getByRole('link', { name: /^savings$/i }).click();
  await expect(page.getByRole('heading', { name: /^savings$/i })).toBeVisible({ timeout: 15_000 });

  // The liability leads, because that is the question the office is asked.
  await expect(page.getByText(/held for suppliers/i)).toBeVisible({ timeout: 15_000 });

  const accounts = page.getByRole('table', { name: /savings accounts/i });
  await expect(accounts.locator('tbody tr').first()).toBeVisible({ timeout: 15_000 });

  await accounts.locator('tbody tr').first().click();
  await expect(page.getByRole('dialog')).toBeVisible();
  await expect(page.getByRole('table', { name: /savings movements/i })).toBeVisible();
  /**
   * §21.9 as answered: the control is here, and the rule is stated whether or not the
   * window is open — an office that only sees it in April cannot answer the question in
   * March. The test runs in whatever month it runs in, so it asserts the badge that is
   * always there rather than the form that is seasonal.
   */
  await expect(page.getByRole('heading', { name: /taking savings out/i })).toBeVisible();
  await expect(page.getByText(/^(open — April|Opens in April)$/i)).toBeVisible();
  // Interest is recorded and never applied — the half of §21.9 still open.
  await expect(page.getByText(/no withdrawals or interest/i)).toHaveCount(0);
});
