/**
 * The one structural difference from mobile, in code.
 *
 * ```
 * mobile:   APP_CLIENT env var  ─► clients[id]  ─► ThemeProvider  (fixed for the app's life)
 * console:  subdomain / token   ─► GET /config  ─► CSS variables  (per session)
 * ```
 *
 * Mobile hands a resolved `Theme` to React context and components read numbers
 * out of it. The console cannot: Tailwind generates its utility classes at
 * **build** time, and the brand does not exist until a fetch resolves at
 * **runtime**. So the theme is emitted as CSS custom properties on
 * `documentElement`, and Tailwind's tokens are declared as `var()` indirections
 * onto them (see `apps/admin/src/styles/theme.css`).
 *
 * ```
 * --brand-color-primary: #2E8B57   ← written here, at runtime
 * --color-primary: var(--brand-color-primary)   ← declared in @theme, at build time
 * .bg-primary { background-color: var(--color-primary) }   ← generated by Tailwind
 * ```
 *
 * The payoff is that the golden rule survives on the web: `bg-primary` is
 * brand-driven, and `bg-[#128C7E]` is a lint error.
 *
 * This module is also where **dp becomes px**. The scale tokens are shared with
 * a React Native bundle and are therefore unitless; this is the only place that
 * decides what unit they mean.
 */

import type { Theme, ThemeOverride } from './types';
import { numericFontFeatures } from './tokens';

/** `primaryContrast` → `primary-contrast`. */
export function kebab(value: string): string {
  return value.replace(/([a-z0-9])([A-Z])/g, '$1-$2').toLowerCase();
}

/** The prefix every runtime-written property carries. */
export const BRAND_VAR_PREFIX = '--brand';

/**
 * Colour values that may be written into a style declaration.
 *
 * Served theme values are **factory-authored content** — someone types them into
 * M14 — so they are validated before being applied, the same way the app
 * validates a promo banner's action URL before acting on it. A malformed value
 * is dropped and the base token stands, which degrades to "unbranded but
 * working" rather than "broken stylesheet".
 */
const SAFE_COLOR = /^(#[0-9a-f]{3,8}|(rgb|hsl)a?\([0-9.,%\s/deg]+\)|[a-z]{3,20})$/i;

export function isSafeColorValue(value: unknown): value is string {
  return typeof value === 'string' && value.length <= 64 && SAFE_COLOR.test(value.trim());
}

/** Finite, non-negative, and small enough not to blow a layout apart. */
export function isSafeScaleValue(value: unknown): value is number {
  return typeof value === 'number' && Number.isFinite(value) && value >= 0 && value <= 10000;
}

/**
 * Flatten a resolved theme into the custom properties the stylesheet expects.
 *
 * Returned rather than applied so this stays pure and testable — `applyTheme`
 * is the side effect.
 */
export function themeToCssVars(theme: Theme): Record<string, string> {
  const vars: Record<string, string> = {};

  for (const [token, value] of Object.entries(theme.colors)) {
    if (!isSafeColorValue(value)) continue;
    vars[`${BRAND_VAR_PREFIX}-color-${kebab(token)}`] = value;
  }

  // dp → px happens here, and only here.
  for (const [token, value] of Object.entries(theme.spacing)) {
    if (!isSafeScaleValue(value)) continue;
    vars[`${BRAND_VAR_PREFIX}-space-${kebab(token)}`] = `${value}px`;
  }

  for (const [token, value] of Object.entries(theme.radius)) {
    if (!isSafeScaleValue(value)) continue;
    vars[`${BRAND_VAR_PREFIX}-radius-${kebab(token)}`] = `${value}px`;
  }

  for (const [token, value] of Object.entries(theme.iconSizes)) {
    if (!isSafeScaleValue(value)) continue;
    vars[`${BRAND_VAR_PREFIX}-icon-${kebab(token)}`] = `${value}px`;
  }

  for (const [key, family] of Object.entries(theme.typography.fontFamily)) {
    vars[`${BRAND_VAR_PREFIX}-font-family-${kebab(key)}`] = family;
  }

  for (const [name, variant] of Object.entries(theme.typography.variants)) {
    const slug = kebab(name);
    vars[`${BRAND_VAR_PREFIX}-font-size-${slug}`] = `${variant.fontSize}px`;
    vars[`${BRAND_VAR_PREFIX}-line-height-${slug}`] = `${variant.lineHeight}px`;
    vars[`${BRAND_VAR_PREFIX}-font-weight-${slug}`] = String(variant.fontWeight);
    vars[`${BRAND_VAR_PREFIX}-letter-spacing-${slug}`] = `${variant.letterSpacing ?? 0}px`;
    // Each variant resolves its logical family key to a real stack, so a
    // component sets one property instead of two.
    vars[`${BRAND_VAR_PREFIX}-font-stack-${slug}`] =
      theme.typography.fontFamily[variant.fontFamily];
  }

  vars[`${BRAND_VAR_PREFIX}-numeric-features`] = numericFontFeatures;

  return vars;
}

/**
 * Write a theme onto an element (normally `document.documentElement`).
 *
 * Returns the property names written, so a caller can clean up when the tenant
 * changes — a platform admin switching tenants must not leave the previous
 * factory's `secondary` behind because the new one does not override it.
 */
export function applyTheme(element: HTMLElement, theme: Theme): string[] {
  const vars = themeToCssVars(theme);
  for (const [property, value] of Object.entries(vars)) {
    element.style.setProperty(property, value);
  }
  element.dataset.scheme = theme.scheme;
  element.style.colorScheme = theme.scheme;
  return Object.keys(vars);
}

/** Remove previously written brand properties. Pair with `applyTheme`. */
export function clearTheme(element: HTMLElement, properties: string[]): void {
  for (const property of properties) element.style.removeProperty(property);
}

/* ─────────────────── Served payload → typed override ─────────────────── */

/**
 * The wire shape of a theme override. Structural on purpose: `@tfd/brand` does
 * not import `@tfd/domain`, so neither package can pull the other into a build
 * that does not need it.
 */
export interface ThemeOverrideWire {
  colors?: { light?: Record<string, string>; dark?: Record<string, string> };
  radius?: Record<string, number>;
  spacing?: Record<string, number>;
}

/**
 * Convert a served override into a typed one, dropping anything unrecognised.
 *
 * Unknown token names are **silently ignored rather than passed through**. A
 * backend that invents `colors.brandNew` is describing a token this build has
 * no utility class for; writing it would produce a dead custom property and the
 * appearance of a working rebrand.
 */
export function themeOverrideFromWire(
  wire: ThemeOverrideWire | undefined,
  known: {
    colorTokens: readonly string[];
    spacingTokens: readonly string[];
    radiusTokens: readonly string[];
  },
): ThemeOverride {
  if (!wire) return {};

  const pickColors = (input?: Record<string, string>) => {
    if (!input) return undefined;
    const out: Record<string, string> = {};
    for (const [token, value] of Object.entries(input)) {
      if (known.colorTokens.includes(token) && isSafeColorValue(value)) out[token] = value;
    }
    return Object.keys(out).length ? out : undefined;
  };

  const pickScale = (input: Record<string, number> | undefined, tokens: readonly string[]) => {
    if (!input) return undefined;
    const out: Record<string, number> = {};
    for (const [token, value] of Object.entries(input)) {
      if (tokens.includes(token) && isSafeScaleValue(value)) out[token] = value;
    }
    return Object.keys(out).length ? out : undefined;
  };

  return {
    colors: {
      light: pickColors(wire.colors?.light),
      dark: pickColors(wire.colors?.dark),
    },
    spacing: pickScale(wire.spacing, known.spacingTokens),
    radius: pickScale(wire.radius, known.radiusTokens),
  } as ThemeOverride;
}
